// <auto-generated />
namespace INFRAESTRUCTURE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Jonathan2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jonathan2));
        
        string IMigrationMetadata.Id
        {
            get { return "202106011753081_Jonathan2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
